name: boltz
channels:
  - conda-forge
  - bioconda
  - biocore

dependencies:
  - python=3.12
  - pip
  - pip:
      - git+https://github.com/jscgh/boltz.git@main
      - torch>=2.2.0 --index-url https://download.pytorch.org/whl/rocm6.2.4
