name: boltz
channels:
  - conda-forge
  - bioconda
  - biocore

dependencies:
  - python=3.12
  - pip
  - pip:
      - git+https://github.com/jwohlwend/boltz.git@main
      - torch==2.5.1+rocm6.2 --index-url https://download.pytorch.org/whl/rocm6.2.4
